### ISSUE TITLE
A question about the inputs to Discriminator, Scheduler, and Worker models

### ISSUE THREAD

**Issue by iced-cappuccino** [jesbu1/hidio#8]
Hi, guy. I am very confused about your code. Could you tell me what the inputs (single transition or a sub-trajectory with option length? dimension?) to Discriminator, Scheduler, and Worker models are? When the feature extractor is "StateAction" type, the input (dim?) to the extractor model is just a single action and a single next_state? Thanks!

**Comment by jesbu1** [comment]
The Scheduler acts as a high level policy that takes an action every H steps. So it just receives the current state at the current time, outputs an action, and waits K steps before receiving the next state.

The feature extractor extracts the features to be used fo the Discriminator model. So if the feature extractor is "StateAction", the input is the concatenated state and action to the discriminator. If it's ActionConcat, then it's the concatenated last (up to) K actions.

Finally, the Worker policy is a low-level policy that just gets the last states and actions of the current subtrajectory (current option selected by the Scheduler) as input.

**Comment by iced-cappuccino** [comment]
Thank you very much for your reply! It's really clear!
However, in your paper, "StateAction" feature extractor is marked as "MLP([a_{h,k}, s_{h,k+1}])". Shouldn't there be a bar on the top of a letter indicating the concatenation?

**Comment by jesbu1** [comment]
Sorry I mean concatenation of the current state with the current action. The bar in the paper indicates concatenations a subtrajectory, like with ActionConcat or StateConcat

**Comment by iced-cappuccino** [comment]
Sorry, I really misunderstood.
So the input of "StateAction" feature extractor is the concatenation of the action and the next state, and that of the low-level policy (Worker policy π_{φ}(·|s_{h,k}, u_{h})) is the concatenation of the current state and the current option, not a concatenation of the current subtrajectory. Right?

**Comment by hnyu** [comment]
Hi, @iced-cappuccino . The low-level policy always use a temporal concatenation of the subtrajectory's states/actions. See 

https://github.com/jesbu1/hidio/blob/fc6b4273180543f049d2650c928890f414618081/hidio/algorithm/hierarchical_agent.py#L43 (input tensor spec)
https://github.com/jesbu1/hidio/blob/fc6b4273180543f049d2650c928890f414618081/hidio/algorithm/hierarchical_agent.py#L160 (make inputs for the low-level policy)
https://github.com/jesbu1/hidio/blob/fc6b4273180543f049d2650c928890f414618081/hidio/examples/hierarchical_goaltask.gin#L46 (configure the low-level networks)

Our code should follow exactly what has been described in the paper. If there is a bar over a quantity, then it's a subtrajectory by concatenation over time. Otherwise it's a quantity at a time step. Regardless of which case, all inputs are concatenated/projected-and-summed before being input to a network.

**Comment by iced-cappuccino** [comment]
![image](https://user-images.githubusercontent.com/64455558/183356187-9471d34f-9eff-4666-94e3-78cdeccd497a.png)
Emmmmm, as shown in your pseudo code, are `s_{h,k}` and `u_{h}` the current state and the current option respectively?

**Comment by hnyu** [comment]
> ![image](https://user-images.githubusercontent.com/64455558/183356187-9471d34f-9eff-4666-94e3-78cdeccd497a.png) Emmmmm, as shown in your pseudo code, are `s_{h,k}` and `u_{h}` the current state and the current option respectively?

@iced-cappuccino  sorry for your confusion. That must be a typo. Please refer to Eq 4 for the correct notation. 

In short, because the discriminator might take a subtrajectory to compute the intrinsic reward for the worker policy, its MDP is no longer Markovian, unless we consider the history of the subtrajectory. For simplicity, we just concatenate time steps temporally, but you can use other working memory such as RNNs. 

Thanks for pointing out this. We'll update the paper for the arXiv version. 

@jesbu1 Can you also confirm the typo?

**Comment by jesbu1** [comment]
Yes there's a typo in the pseudocode and also in Eq 2. 

Thanks for catching this! I'll be uploading a new arxiv version.

**Comment by iced-cappuccino** [comment]
Oh, I see!
Really thanks for your help!
Have a good day, guy!
